### PR TITLE
Echidna part numbers

### PR DESCRIPTION
**Pull request by dalexander**
(I intend to remove the comments and whitespace before merging)

### CODE REVIEW

**Comment by dalexander** [comment]
also, I intend to merge this to `smrtanalysis-3.1.0` branch first.  I screwed up the PR creation.

**Comment by dalexander** [comment]
in reviewing this, I note that I didn't call the 1.1/1.1 condition "prospective".  My reasoning there was that if we name the chemistry 1.x/1.y, it had  _better_ be compatible, so I was assuming some knowledge about it.  Even though, in truth, this is a chemistry we haven't seen yet.

**Comment by nlhepler** [comment]
I'm a bit uncomfortable with the assumption about the 1.x/1.y thing, because I don't think we have the institutional QA procedures to guarantee that, despite their necessity. Otherwise, +1

**Comment by dalexander** [comment]
this has been pushed in a separate commit

**Pull request closed without merging**
