### PR TITLE
workaround for empty indexed fasta

### PR DESCRIPTION
**Pull request by natechols**
It's not lovely, but this is a valid use case, and I'm pretty sure it won't have side effects.

### CODE REVIEW

**Comment by natechols** [comment]
Yes, it's definitely a corner case, but the IsoSeq protocol may come up empty for one of the final outputs (which probably means the overall experiment was a failure, but the pipeline still runs OK).  I'm cheating in pbtranscript by writing an empty .fai file when this happens - this keeps the DataSet API happy.

**Comment by mpkocher** [comment]
Would it possible to make the default behavior of openDataset raise an empty exception if the file is empty? This would make the error very clear in downstream tools.

Something along the lines:

`openDataset("/path/to/dataset.xml", suppressEmpty=False)`

For most tools, an input of an empty dataset is going to going to yield unclear or undefined behavior with perhaps not the clearest error message. For cases where the tool can support an empty dataset (e.g., gathering tool), then it can catch the EmptyDataSetException, or suppress the default behavior with a kw.

**Comment by dalexander** [comment]
@mdsmith can opine on the dataset questions.

In general I believe empty files are valid, it's an application-level question as to whether they make sense or not---not a pbcore-level question.

**Comment by natechols** [comment]
I agree with Dave, the handling of empty files should be left to the application - it has actually been a real pain for testing tiny datasets where it is very common for chunked tasks to produce empty outputs.

**Comment by mdsmith** [comment]
Looks fine to me. Handling empty files has long been tricky, as some Readers support it better than others, and at some points it made sense to use empty Readers while at others it made sense to ignore the files all together. If this solves the problem, great, if not I'll do a deeper reorganization of the DataSet API design.

**Comment by natechols** [comment]
I think it would be preferable in the future to ignore empty files altogether - but this requires that the XSD be changed first to allow empty ExternalResources.  (There may be other valid reasons why this is a bad idea.)

**Pull request merged**
