### PR TITLE
Update URL to download hdf5 1.8.12 in CI

### PR DESCRIPTION
**Pull request by llimeht**
(Spotted while trying to debug failing tests of pbcore with Python 3.7 and numpy 1.16)

### CODE REVIEW

**Comment by pb-dseifert** [comment]
That's very attentive, but does this break any workflow of yours? We should decommission our CircleCI scripts anwyays, since we aren't using them anymore.

**Comment by llimeht** [comment]
That particular change fixes nothing for me, it was just a starting point to fix the bugs in pbone. Perhaps lack of functional CI is why you don't know that pbone is broken with numpy 1.16 ;) It is currently unbuildable and unusable and is therefore holding up the distro's migration to numpy 1.16.


    ======================================================================
    ERROR: test_pbcore_io_AlnFileReaders.TestBasicBam.testBaxAttaching
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    File "/tmp/autopkgtest-lxc.pmgizopx/downtmp/build.uL8/src/tests/test_pbcore_io_AlnFileReaders.py", line 293, in testBaxAttaching
        self.f.attach(self.BAX_FILE)
    File "/usr/lib/python2.7/dist-packages/pbcore/io/align/_AlignmentMixin.py", line 22, in attach
        self.basH5Collection = BasH5Collection(fofnFilename)
    File "/usr/lib/python2.7/dist-packages/pbcore/io/BasH5IO.py", line 817, in __init__
        for k, v in groupby(movieNamesAndFiles, lambda t: t[0]) ])
    File "/usr/lib/python2.7/dist-packages/pbcore/io/BasH5IO.py", line 661, in __init__
        self._parts = [ BaxH5Reader(self.filename) ]
    File "/usr/lib/python2.7/dist-packages/pbcore/io/BasH5IO.py", line 328, in __init__
        self._loadRegions(self.file)
    File "/usr/lib/python2.7/dist-packages/pbcore/io/BasH5IO.py", line 355, in _loadRegions
        self._regionTableIndex = _makeRegionTableIndex(self.regionTable.holeNumber)
    File "/usr/lib/python2.7/dist-packages/pbcore/io/BasH5IO.py", line 284, in _makeRegionTableIndex
        to_begin=[1], to_end=[1])
    File "/usr/lib/python2.7/dist-packages/numpy/lib/arraysetops.py", line 111, in ediff1d
        raise TypeError("dtype of to_begin must be compatible "
    TypeError: dtype of to_begin must be compatible with input ary

and many more: https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-pbcore/1663499/log.gz

**Comment by pb-dseifert** [comment]
@llimeht correct, we're using numpy 1.15 internally (also because awful h5py spews out weird warnings with 1.16). Happy to accept patches. Maybe we should keep CircleCI going for the latest versions of dependencies.

**Comment by pb-dseifert** [comment]
Also, don't even think about trying Python 3 with pbcore. It's not Python 3 ready yet. This is on our radar, just not high priority right now.

**Comment by pb-dseifert** [comment]
@llimeht does it pass on numpy 1.16 now? I've tried it on our internal CI and it seemed to have passed with my fix

**Comment by llimeht** [comment]
Yes, with the patch from @RizzerOnGithub, it now builds with 1.16-rc2: https://buildd.debian.org/status/fetch.php?pkg=python-pbcore&arch=all&ver=1.6.5%2Bdfsg-1&stamp=1547119099&raw=0

Thanks!

**Pull request closed without merging**
