### PR TITLE
Expand Dataset summarize. Display default commandline options.

### PR DESCRIPTION
**Pull request by mpkocher**

### CODE REVIEW

**Comment by dalexander** [comment]
@mpkocher, can you get rid of the duplicate commits?  Then i will merge

**Comment by dalexander** [comment]
(assuming this chang is OK with @mdsmith)

**Comment by mdsmith** [comment]
Looks good to me.

**Comment by dalexander** [comment]
@mpkocher please rebase this?  In general it's best to submit PRs from topic branches, not `master`, to avoid this kind of problem

**Pull request closed without merging**
