### PR TITLE
Test and fix for empty mapped BAM pbi issue.

### PR DESCRIPTION
**Pull request by dalexander**
(Rebases Nat's PR code, cleans up a bit, and fixes/works around the issue as best we can)

### CODE REVIEW

**Comment by dalexander** [comment]
@mdsmith please review this martin?

**Comment by mdsmith** [comment]
What is the new expected behavior upon index.tId accession for an empty mapped file (previously AttributeError, but the check was removed from the dataset test file)? Do we still raise an AttributeError, and expect users to check if there are reads first, or is now working smoothly and implicitly used/tested in IndexBamReader.readsInRange?

**Comment by dalexander** [comment]
> What is the new expected behavior upon index.tId accession for an empty mapped file (previously AttributeError, but the check was removed from the dataset test file)? 

It will return an empty array

I don't understand your latter question.

**Comment by mdsmith** [comment]
Looks great.

**Comment by dalexander** [comment]
ok will merge

**Pull request merged**
