### PR TITLE
Identity Calculation Fix

### PR DESCRIPTION
**Pull request by vrainish-pacbio**

### CODE REVIEW

**Comment by dalexander** [comment]
so obviously we're not going to merge this until we've had a broader discussion with aaron.  and the test would need to be fixed.

**Comment by dalexander** [comment]
and I'm not even sure this is the calculation we want to use.  If we're going to fix things, I think the preferred denominator is either the template length or the alignment length.

**Comment by natechols** [comment]
The test is failing because this isn't the only place where identity is calculated - there is a fast array equivalent in BamIO.py that uses the .pbi index, which will also need to be changed.

**Comment by evolvedmicrobe** [comment]
Speaking for internal tools, we are going to define the accuracy as the expected number of errors per sequenced template base going forward - I am not sure why the read length ever made sense, but this definition seems very strange to me.

**Pull request closed without merging**
